import{i as a,S as f}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&o(c)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();async function m(r){const n=`https://pixabay.com/api/?key=45488141-0a4a6f9550d86e9b8ad8f4cbd&q=${r}&image_type=photo&orientation=horizontal&safesearch=true`,o=await fetch(n);if(!o.ok)throw new Error("Network response was not ok");return o.json()}function g(r){const t=document.querySelector(".gallery"),n=r.map(o=>`
    <a href="${o.largeImageURL}">
      <img src="${o.webformatURL}" alt="${o.tags}" loading="lazy"/>
      <div class="info">
        <p>Likes: ${o.likes}</p>
        <p>Views: ${o.views}</p>
      </div>
    </a>
  `).join("");t.innerHTML=n}let l;const h=document.querySelector("#search-form"),y=document.querySelector(".gallery"),u=document.querySelector(".load-more");let i="",d=1;h.addEventListener("submit",p);u.addEventListener("click",w);async function p(r){if(r.preventDefault(),i=r.currentTarget.elements.searchQuery.value.trim(),!i){a.error({title:"Error",message:"Please enter a search term!"});return}y.innerHTML="",d=1,u.classList.add("is-hidden");try{const t=await m(i);t.hits.length===0?a.warning({title:"Warning",message:"No images found!"}):(g(t.hits),l=new f(".gallery a"),u.classList.remove("is-hidden"))}catch(t){a.error({title:"Error",message:`Something went wrong: ${t.message}`})}}async function w(){d+=1;try{const r=await m(i,d);g(r.hits),l=new f(".gallery a"),l.refresh()}catch(r){a.error({title:"Error",message:`Something went wrong: ${r.message}`})}}
//# sourceMappingURL=commonHelpers.js.map
